version: "3"
services:
  web:
    build: .
    environment:
      - "REDIS_URL=redis://redis:6379"
      - TZ=Asia/Tokyo
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
    #    depends_on:
    #      - db
    #      - redis
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    links:
      - db
      - redis

  redis:
    image: redis
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "6379:6379"

  db:
    image: mysql:5.7
    environment:
      # 仮のパスワードを設定している
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
